config:
    use_colors: True 
default:
  outputs:
    dev:
      type: postgres
      threads: 1
      host: localhost
      port: 5432
      user: postgres  #"{{ env_var('USERNAME') }}"
      pass: postgres  #"{{ env_var('PASSWORD') }}"
      dbname: dvd_rental
      schema: dev
    prod:
      type: postgres
      threads: 1
      host: localhost
      port: 5432
      user: postgres #"{{ env_var('USERNAME') }}"
      pass: postgres #"{{ env_var('PASSWORD') }}"
      dbname: dvd_rental
      schema: analytics
  target: dev
